/* 
DDL commands to set up tables in
the database. Using the database test 
installed with MySQL.
*/
USE test;
DROP TABLE IF EXISTS STAFF_DATA;
DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF (
  EMP_ID INTEGER (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
CREATE TABLE STAFF_DATA (
  RECORD_ID INTEGER(10)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMP_ID INTEGER (10) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE NOT NULL,
  SALARY DECIMAL (20, 4) NOT NULL,
  ADDRESS VARCHAR (50) NOT NULL,
  IS_DELETED TINYINT (1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  FOREIGN KEY (EMP_ID) REFERENCES STAFF(EMP_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  INDEX (EMP_ID, VERSION)
);
DROP TABLE IF EXISTS COHORT_DATA;
DROP TABLE IF EXISTS COHORT;
CREATE TABLE COHORT 
(STUDENT_ID INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
CREATE TABLE COHORT_DATA (
  RECORD_ID INTEGER(10)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  STUDENT_ID INTEGER (10) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE,
  CITY_ID int(11) NOT NULL,
  IS_DELETED TINYINT (1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  FOREIGN KEY (CITY_ID) REFERENCES US_CITIES(CITY_ID)
  ON DELETE RESTRICT
  ON UPDATE CASCADE,
  FOREIGN KEY (STUDENT_ID) REFERENCES COHORT(STUDENT_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  INDEX (STUDENT_ID, VERSION)
);
DROP TABLE IF EXISTS COURSES_DATA;
DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES (
  COURSE_ID CHAR (6) NOT NULL PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
CREATE TABLE COURSES_DATA (
  RECORD_ID INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COURSE_ID CHAR (6) NOT NULL,
  DEPARTMENT_ID CHAR (6) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  TITLE VARCHAR (20) NOT NULL,
  DESCRIPTION VARCHAR (30) DEFAULT '',
  IS_DELETED TINYINT (1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  INDEX (COURSE_ID,VERSION)
);
DROP TABLE IF EXISTS WORKER_DATA;
DROP TABLE IF EXISTS WORKER;
CREATE TABLE WORKER
(WORKER_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
CREATE TABLE WORKER_DATA
(RECORD_ID INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  WORKER_ID INT(11) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE NOT NULL,
  IS_DELETED TINYINT (1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  FOREIGN KEY (WORKER_ID) REFERENCES WORKER(WORKER_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  INDEX (WORKER_ID,VERSION)
);

DROP TABLE IF EXISTS FACULTY_DATA;
DROP TABLE IF EXISTS FACULTY;
CREATE TABLE FACULTY
(INSTRUCTOR_ID integer (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
CREATE TABLE FACULTY_DATA
(RECORD_ID INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INSTRUCTOR_ID integer (10) NOT NULL,
  DEPARTMENT_ID CHAR (6) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) NOT NULL DEFAULT '',
  POSITION VARCHAR (25),
  ADDRESS VARCHAR (50),
  IS_DELETED TINYINT (1) NOT NULL DEFAULT 0,
  CREATION_DATE TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR (20) NOT NULL,
  FOREIGN KEY (INSTRUCTOR_ID) REFERENCES FACULTY(INSTRUCTOR_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  INDEX (INSTRUCTOR_ID,VERSION)
);
