/* 
DDL commands to set up tables in
the database. Using the database test 
installed with MySQL.
*/
USE test;
DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF (
  EMP_ID INTEGER (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE NOT NULL,
  SALARY DECIMAL (20, 4) NOT NULL,
  ADDRESS VARCHAR (50) NOT NULL
);
DROP TABLE IF EXISTS COHORT;
CREATE TABLE COHORT (
  STUDENT_ID INTEGER (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE,
  CITY_ID int(11) NOT NULL,
  FOREIGN KEY (CITY_ID) REFERENCES US_CITIES(CITY_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES (
  COURSE_ID CHAR (6) NOT NULL PRIMARY KEY,
  DEPARTMENT_ID CHAR (6) NOT NULL,
  TITLE VARCHAR (20) NOT NULL,
  DESCRIPTION VARCHAR (30) DEFAULT ''
);
INSERT INTO COHORT (FIRST_NAME,LAST_NAME,
MIDDLE_NAME,BIRTH_DATE, CITY_ID)
VALUES ('John', 'Smith', '', '1960-08-09',
1);
