/* 
DDL commands to set up tables in
the database. Using the database test 
installed with MySQL.
*/
USE test;
DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF (
  EMP_ID INTEGER (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL
  CREATED_BY VARCHAR (20) NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
DROP TABLE IF EXISTS STAFF_DATA;
CREATE TABLE STAFF_DATA (
  RECORD_ID INTEGER(10)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMP_ID INTEGER (10) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE NOT NULL,
  SALARY DECIMAL (20, 4) NOT NULL,
  ADDRESS VARCHAR (50) NOT NULL,
  FOREIGN KEY (EMP_ID) REFERENCES STAFF(EMP_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
DROP TABLE IF EXISTS COHORT;
CREATE TABLE COHORT (
  STUDENT_ID INTEGER (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL
  CREATED_BY VARCHAR (20) NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL,
);
DROP TABLE IF EXISTS COHORT_DATA;
CREATE TABLE COHORT_DATA (
  RECORD_ID INTEGER(10)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  STUDENT_ID INTEGER (10) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE,
  CITY_ID int(11) NOT NULL,
  FOREIGN KEY (CITY_ID) REFERENCES US_CITIES(CITY_ID)
  ON DELETE RESTRICT
  ON UPDATE CASCADE,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
DROP TABLE IF EXISTS COURSES;
CREATE TABLE COURSES (
  COURSE_ID CHAR (6) NOT NULL PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL
  CREATED_BY VARCHAR (20) NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
DROP TABLE IF EXISTS COURSES_DATA;
CREATE TABLE COURSES_DATA (
  RECORD_ID INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COURSE_ID CHAR (6) NOT NULL,
  DEPARTMENT_ID CHAR (6) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  TITLE VARCHAR (20) NOT NULL,
  DESCRIPTION VARCHAR (30) DEFAULT '',
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
DROP TABLE IF EXISTS WORKER;
CREATE TABLE WORKER
(WORKER_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CURRENT_VERSION INTEGER(10) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL
  CREATED_BY VARCHAR (20) NOT NULL,
  UPDATED_BY VARCHAR (20) NOT NULL
);
DROP TABLE IF EXISTS WORKER_DATA;
CREATE TABLE WORKER_DATA
(RECORD_ID INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  WORKER_ID INT(11) NOT NULL,
  VERSION INTEGER(10) NOT NULL,
  FIRST_NAME VARCHAR (20) NOT NULL,
  LAST_NAME VARCHAR (20) NOT NULL,
  MIDDLE_NAME VARCHAR (20) DEFAULT '',
  BIRTH_DATE DATE NOT NULL,
  FOREIGN KEY (WORKER_ID) REFERENCES WORKER(WORKER_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
