#!/usr/bin/env bash

function usage() {
echo "Usage: $0 <dir>|<file>"
echo "dir - directory"
echo "file - sql file"
exit 1
}

if [[ $# -ne 1 ]];
then
  usage
fi

if [[ ! -d "$1" ]] && [[ ! -f "$1" ]]
then 
  usage
fi

if [[ -d "$1" ]];
then
  echo "Processing directory $1"
  find "$1" -name "*.sql" \
    | parallel sql-formatter-cli -i {} -o {} -s "sql"
      exit "$?"
fi

if [[ -f "$1" ]];
then
  echo "Processing file $1"
  sql-formatter-cli -i "$1" -o "$1" -s "sql"
  exit "$?"
fi
