USE test;
--
-- Table structure for table `us_states`
--

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS US_STATES;
CREATE TABLE US_STATES (
	STATE_CODE char(2) NOT NULL,
	STATE_NAME varchar(50) NOT NULL,
	PRIMARY KEY (STATE_CODE)
);

INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('AL','Alabama');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('AK','Alaska');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('AZ','Arizona');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('AR','Arkansas');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('CA','California');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('CO','Colorado');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('CT','Connecticut');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('DE','Delaware');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('DC','District of Columbia');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('FL','Florida');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('GA','Georgia');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('HI','Hawaii');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('ID','Idaho');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('IL','Illinois');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('IN','Indiana');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('IA','Iowa');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('KS','Kansas');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('KY','Kentucky');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('LA','Louisiana');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('ME','Maine');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MD','Maryland');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MA','Massachusetts');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MI','Michigan');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MN','Minnesota');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MS','Mississippi');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MO','Missouri');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('MT','Montana');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NE','Nebraska');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NV','Nevada');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NH','New Hampshire');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NJ','New Jersey');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NM','New Mexico');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NY','New York');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('NC','North Carolina');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('ND','North Dakota');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('OH','Ohio');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('OK','Oklahoma');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('OR','Oregon');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('PA','Pennsylvania');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('PR','Puerto Rico');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('RI','Rhode Island');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('SC','South Carolina');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('SD','South Dakota');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('TN','Tennessee');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('TX','Texas');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('UT','Utah');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('VT','Vermont');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('VA','Virginia');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('WA','Washington');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('WV','West Virginia');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('WI','Wisconsin');
INSERT INTO US_STATES (STATE_CODE, STATE_NAME) VALUES
('WY','Wyoming');

--
-- Table structure for table `us_cities`
--

DROP TABLE IF EXISTS US_CITIES;
CREATE TABLE US_CITIES (
	CITY_ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATE_CODE CHAR(2) NOT NULL,
	CITY varchar(50) NOT NULL,
	COUNTY varchar(50) NOT NULL,
	LATITUDE double NOT NULL,
	LONGITUDE double NOT NULL,
  FOREIGN KEY (STATE_CODE) REFERENCES US_STATES(STATE_CODE)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

SET FOREIGN_KEY_CHECKS=1;

INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE) 
VALUES ('NY','New York','New York',40.74838,-73.996705);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE) VALUES 
('CA','Los Angeles','Los Angeles',33.973093,-118.247896);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('IL','Chicago','Cook',41.885847,-87.618123);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('TX','Houston','Harris',29.7652,-95.3657);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('AZ','Phoenix','Maricopa',33.451,-112.0685);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('PA','Philadelphia','Philadelphia',40.1162,-75.0141);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('TX','San Antonio','Bexar',29.468525,-98.526352);
INSERT INTO US_CITIES 
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('CA','San Diego','San Diego',32.71852,-117.159316);
INSERT INTO US_CITIES
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('TX','Dallas','Dallas',32.790439,-96.80439);
INSERT INTO US_CITIES
(STATE_CODE,CITY,COUNTY,LATITUDE,LONGITUDE)  VALUES
('CA','San Jose','Santa Clara',37.3894,-121.8868);
