#!/usr/bin/env bash
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql

# Starting the database

pg_ctl -D $PREFIX/var/lib/postgresql start


# Create User

createuser --superuser --pwprompt adminpgsql
# password: postgresql
# Create your database:

createdb mydb

# Open your database

psql mydb

# Similarly stop the database using

pg_ctl -D $PREFIX/var/lib/postgresql stop
